"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$username\
[](bg:blue fg:mauve)\
$directory\
[](bg:sky fg:blue)\
$git_branch\
$git_status\
[](fg:sky)\
$fill\
$cmd_duration\
[](sky)\
$dotnet\
$rust\
$python\
$time\
[](sky)\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:mauve fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
CachyOS = "󰣇"

# configs
[username]
show_always = true
style_user = "bg:mauve fg:crust"
style_root = "bg:mauve fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:sky"
format = '[[ $symbol $branch ](fg:crust bg:sky)]($style)'

[git_status]
style = "bg:sky"
format = '[[($all_status$ahead_behind )](fg:crust bg:sky)]($style)'

[fill]
symbol = '-'
style = 'bold sky'

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M:%S" # 24-hour format (e.g., 14:30:45)
style = "bg:sky fg:crust"

[cmd_duration]
min_time = 2000
style = "fg:sky"
format = " [$duration]($style) "

# languages
[rust]
symbol = ""
style = "fg:crust bg:sky"
format = '[ $symbol( $version) ]($style)'

[dotnet]
symbol = ""
style = "fg:crust bg:sky"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:crust bg:sky"
format = '[ $symbol( $version) ]($style)'

# palettes
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

